### Put String
POST http://localhost:1313/api/v1/string/put
Content-Type: application/json

{
    "key": "k",
    "value": "v"
}

### Get String
POST http://localhost:1313/api/v1/string/get
Content-Type: application/json

{
    "key": "k"
}
